export const fonts = {
    bai: {
      black: 'BaiJamjuree-Bold',
      blackItalic: 'BaiJamjuree-BoldItalic',
      extraLight: 'BaiJamjuree-ExtraLight',
      extraLightItalic: 'BaiJamjuree-ExtraLightItalic',
      italic: 'BaiJamjuree-Italic',
      light: 'BaiJamjuree-Light',
      lightItalic: 'BaiJamjuree-LightItalic',
      medium: 'BaiJamjuree-Medium',
      mediumItalic: 'BaiJamjuree-MediumItalic',
      regular: 'BaiJamjuree-Regular',
      semiBold: 'BaiJamjuree-SemiBold',
      semiBoldItalic: 'BaiJamjuree-SemiBoldItalic',
    },
    montserrat: {
      black: 'MontserratAlternates-Black',
      blackItalic: 'MontserratAlternates-BlackItalic',
      bold: 'MontserratAlternates-Bold',
      boldItalic: 'MontserratAlternates-BoldItalic',
      extraBold: 'MontserratAlternates-ExtraBold',
      extraBoldItalic: 'MontserratAlternates-ExtraBoldItalic',
      extraLight: 'MontserratAlternates-ExtraLight',
      extraLightItalic: 'MontserratAlternates-ExtraLightItalic',
      italic: 'MontserratAlternates-Italic',
      light: 'MontserratAlternates-Light',
      lightItalic: 'MontserratAlternates-LightItalic',
      medium: 'MontserratAlternates-Medium',
      mediumItalic: 'MontserratAlternates-MediumItalic',
      regular: 'MontserratAlternates-Regular',
      semiBold: 'MontserratAlternates-SemiBold',
      semiBoldItalic: 'MontserratAlternates-SemiBoldItalic',
      thin: 'MontserratAlternates-Thin',
      thinItalic: 'MontserratAlternates-ThinItalic',
    },
  };
  